[QUICKORDER-18] IS autocomplete
vtex-apps/quickorder pull request #114
Opened 2022-04-12 03:49 UTC by aurorahey

What does this PR do? *

Replace the autocomplete search query with the intelligent search autocomplete

How to test it? *

Go to workspace [https://aurora--b2bstoreqa.myvtex.com/quickorder](https://github.com/vtex-apps/quickorder/compare/bugfix/url), and login to your account. Input keyword in the autocomplete block, you should now only see the assigned product collection

2022-04-12 14:11 UTC, arturmagalhaesjr reviewed
I got this error when I've tested:
<img width="2207" alt="image" src="https://user-images.githubusercontent.com/5812946/162981626-93583f44-7212-46ba-9dac-e7e172975c0c.png">

2022-05-04 17:36 UTC, arturmagalhaesjr requested changes
I found a minor issue when  I was testing and I encourage you to fix it,
It's not related to your PR, but you can leverage it to solve.
I think that you should turn it as disabled when the quantity is 0, what do you think?

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/5812946/166744755-576bab92-1f3a-41e3-b447-99b7a69dea63.png">

2022-05-04 17:54 UTC, aurorahey commented
> 

Hey Artur, thank you for your review. 
I think we better work on it on another ticket since The version "[3.8.1] - Fixed the issue that the autocomplete block quantity button was starting with 0 instead of 1." is regarding this issue. We better spend more time investigating why doesn't the 3.8.1 work on some items.

2022-05-05 01:11 UTC, arturmagalhaesjr approved these changes
LGTM

2022-05-05 01:38 UTC, merged