Removed validation that hid the add to cart button when there was an …
vtex-apps/quickorder pull request #157
Opened 2023-07-27 18:34 UTC by jailsonacct

…invalid SKU

#### What does this PR do? \*
Removed a validation that prevented the "Add to cart" button from appearing below the table of items added via spreadsheet.
Before: The button only appeared if the user removed invalid items.
After: The button appears even if it has an invalid SKU.
As there is already a validation when adding to the cart, only valid SKUs will be added, the others will be ignored. There is no need for the customer to manually remove these items.

#### How to test it? \*

Access the workspace [](https://qta38--lojaobramax.myvtex.com/quickorder) and add a worksheet with SKUS, valid and invalid.
Click on the add to cart button, which will now appear. Valid items must be added to the cart.

SKU's list
[prods_with_invalids.xlsx](https://github.com/vtex-apps/quickorder/files/12186702/prods_with_invalids.xlsx)

#### Related to / Depends on \*

### Before
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.07.27-15_32_49.webm](https://github.com/vtex-apps/quickorder/assets/116591771/126269a5-7ee6-4750-872d-9ad177ec72a2)

### After
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.07.27-15_30_48.webm](https://github.com/vtex-apps/quickorder/assets/116591771/09e150cb-e0ab-4d5e-b864-35e5bd33912c)

2023-07-28 13:39 UTC, carlosananias requested changes

2023-07-28 13:39 UTC, carlosananias commented on react/UploadBlock.tsx
>    const onReviewItems = (items: any) => {
@jailsonacct que tal otimizarmos o código com a função some() que retorna um true?

```
const onReviewItems = (items: any) => {
  const { alwaysShowAddToCart, state, setState } = this;

  const show = !items.some((item: any) => item.error);

  setState({
    ...state,
    reviewItems: items,
    reviewState: true,
    showAddToCart: alwaysShowAddToCart || show,
    textAreaValue: GetText(items),
  });
};
```

2023-07-28 13:41 UTC, jailsonacct commented on CHANGELOG.md
> +### Removed
@carlosananias Já tinha mudado para Added devido a adição da prop

2023-08-16 14:35 UTC, Rudge approved these changes

2023-08-17 13:09 UTC, Rudge commented
@jailsonacct The action lint ran after approval and detected some errors. Could you fix them for merge, please?

2023-08-24 11:42 UTC, jailsonacct commented
@Rudge What fixes? I saw that you changed yarn.lock there, which had not been changed before.
![image](https://github.com/vtex-apps/quickorder/assets/116591771/285540ed-09da-4796-bf6c-93f338d823d5)

2023-08-24 13:19 UTC, Rudge commented
> @Rudge What fixes? I saw that you changed yarn.lock there, which had not been changed before. I removed the change in yarn.lock again. ![image](https://user-images.githubusercontent.com/116591771/262961488-285540ed-09da-4796-bf6c-93f338d823d5.png)

@jailsonacct I executed the `npx eslint --ext js,jsx,ts,tsx . --fix` and maybe it updated the yarn.lock too. It isn't a problem to update this file.

2023-08-24 13:24 UTC, Rudge approved these changes

2023-08-24 14:19 UTC, merged